"""Add cascade delete

Revision ID: 5e03aa6ce0f9
Revises: 6e7a8b9c0d1e, 8b5ea8075af7
Create Date: 2026-05-21 12:08:53.119873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e03aa6ce0f9' # This ID might change if you re-autogenerate
down_revision: Union[str, Sequence[str], None] = ('6e7a8b9c0d1e', '8b5ea8075af7') # Add the initial migration as a dependency
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        # Manually drop the column and re-add it to implicitly handle the unnamed FK
        # This is the standard workaround for SQLite's ALTER TABLE limitations in batch mode
        batch_op.drop_column('flow_id')
        batch_op.add_column(sa.Column('flow_id', sa.Integer(), nullable=True)) # Use nullable=True if it was originally nullable
        batch_op.create_foreign_key(batch_op.f('fk_transactions_flow_id_flows'), 'flows', ['flow_id'], ['id'], ondelete='CASCADE')

    # Ensure the 'flow' relationship is also updated in the model if needed,
    # but this migration primarily focuses on the FK constraint.

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_flow_id_flows'), type_='foreignkey')
        # Revert by dropping the column and re-adding the original FK without CASCADE
        batch_op.drop_column('flow_id')
        batch_op.add_column(sa.Column('flow_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transactions_flow_id_flows', 'flows', ['flow_id'], ['id']) # Recreate without cascade

    # ### end Alembic commands ###
