"""Add currency validation fields to Flow

Revision ID: 8ac40dade2d6
Revises: d3aa325e9cb5
Create Date: 2026-06-02 11:23:01.881255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ac40dade2d6'
down_revision: Union[str, Sequence[str], None] = 'd3aa325e9cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_validation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allowed_currency', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.drop_column('allowed_currency')
        batch_op.drop_column('currency_validation')

    # ### end Alembic commands ###
