"""Add flow metadata columns

Revision ID: 8b5ea8075af7
Revises: 
Create Date: 2026-05-18 14:09:36.287771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5ea8075af7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=True),
    sa.Column('destination_system', sa.String(), nullable=True),
    sa.Column('message_format', sa.String(), nullable=True),
    sa.Column('file_format', sa.String(), nullable=True),
    sa.Column('bic_codes', sa.JSON(), nullable=True),
    sa.Column('valid_ibans', sa.JSON(), nullable=True),
    sa.Column('input_path', sa.String(), nullable=True),
    sa.Column('output_path', sa.String(), nullable=True),
    sa.Column('special_character_support', sa.Boolean(), nullable=True),
    sa.Column('back_dated', sa.Boolean(), nullable=True),
    sa.Column('future_dated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flows_id'), 'flows', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=True),
    sa.Column('instruction_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_flows_id'), table_name='flows')
    op.drop_table('flows')
    # ### end Alembic commands ###
